#!/usr/bin/env bash
#install nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sed -i 's/^\(listen\s*.*\)80/\180/' /etc/nginx/sites-available/default
sudo service nginx start
