#!/usr/bin/env bash
# configure a load balancer

function install() {
	command -v "$1" &> /dev/null

	#shellcheck disable=SC2181
	if [ $? -ne 0 ]; then
		echo -e "	Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}

install haproxy #install haproxy

sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend DevBekoDev-FrontEnd
    bind *:80
    default_backend DevBekoDev-FrontEnd

backend DevBekoDev-BackEnd
    balance roundrobin
    server 513870-web-01 52.91.178.111:80 check
    server 513870-web-02 107.20.154.11980 check
"

echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
